# Generated by Django 4.2.7 on 2023-12-10 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=200)),
                ('typecar', models.CharField(default='car', max_length=100)),
                ('img', models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Vintage_blue_car.png/800px-Vintage_blue_car.png', max_length=500)),
                ('price', models.IntegerField(default=9999999)),
                ('mpg', models.IntegerField(default=1000)),
            ],
        ),
    ]
