# Generated by Django 4.2.7 on 2023-12-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=200)),
                ('img_url', models.URLField(max_length=500)),
            ],
        ),
    ]
