# Generated by Django 4.2.7 on 2023-12-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_remove_react_img_url_react_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='price',
            field=models.IntegerField(default=9999999),
        ),
    ]
