# Generated by Django 4.2.7 on 2023-12-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5)),
                ('fullName', models.CharField(max_length=100)),
                ('vehicle', models.CharField(max_length=200)),
                ('comments', models.CharField(max_length=500)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
