# Generated by Django 4.2.7 on 2023-12-04 06:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='img',
            field=models.URLField(default='Burning_Rubber\\React\x08urning-rubber-react\\src\x07ssets\\lambo_tractor.jpg', max_length=1000),
        ),
        migrations.AlterField(
            model_name='review',
            name='comments',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
